spring:

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  kakao:
    client_id: ${kakao.client_id}
    redirect_uri: http://localhost:8080/auth/kakao

  naver:
    client_id: ${naver.client_id}
    secret: ${naver.secret}

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

  jwt:
    secret: ${jwt.secret}
    access-token-validity-in-milliseconds: ${jwt.access-token-validity-in-milliseconds}
    refresh-token-validity-in-milliseconds: ${jwt.refresh-token-validity-in-milliseconds}

  aws:
    s3:
      bucket: ${S3.BURCKET_NAME}
      credentials:
        access-key: ${S3.ACCESS_KEY}
        secret-key: ${S3.SECRET_KEY}
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false