spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: https://front-ruby-eta.vercel.app/oauth/google

  naver:
    client_id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_SECRET}

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-in-milliseconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}
    refresh-token-validity-in-milliseconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_MILLISECONDS}

  aws:
    region:
      static: ${AWS_REGION} #aws s3는 AWS_REGION을 사용해야함.
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      accessKey: ${BUCKET_ACCESS}
      secretKey: ${BUCKET_SECRET}
